package Common;

public enum Commands{
        CMD_GET_ITEMS, CMD_GET_ITEMS_RESP,
        CMD_GET_ENTRIES, CMD_GET_ENTRIES_RESP,
        CMD_GET_USERS, CMD_GET_USERS_RESP,
        CMD_LOGIN, CMD_LOGIN_RESP,
        CMD_REGISTER_CLIENT,
        CMD_REGISTER_EMPLOYEE,
        CMD_CREATE_NEW_ITEM1,
        CMD_CREATE_NEW_ITEM2,
        CMD_BUY_ITEMS, CMD_BUY_ITEMS_RESP,
        CMD_EMPTY_CART,
        CMD_DECREASE_STOCK,
        CMD_INCREASE_STOCK,
        CMD_SELECT_ITEM,
        CMD_REMOVE_ITEM,
        CMD_GET_ITEM_INFO, CMD_GET_ITEM_INFO_RESP,
        CMD_LOGOUT,
        CMD_END_PRICE, CMD_END_PRICE_RESP,
        CMD_GET_ITEMS_IN_CART, CMD_GET_ITEMS_IN_CART_RESP
}